name: Kubernetes Setup Only
trigger: none  # Manual only

pool:
  name: 'Default'

parameters:
- name: action
  displayName: 'Kubernetes Action'
  type: string
  default: 'setup'
  values:
  - setup
  - reset
  - rejoin-workers
  - status
  - restart-services

stages:
- stage: KubernetesAction
  displayName: 'Kubernetes Operations'
  jobs:
  - job: K8sAction
    displayName: 'Kubernetes ${{ parameters.action }}'
    steps:
    - template: ../templates/setup-ssh.yml
    - template: ../templates/generate-inventory.yml
    
    - task: Bash@3
      displayName: 'Kubernetes Action: ${{ parameters.action }}'
      timeoutInMinutes: 30
      inputs:
        targetType: 'inline'
        script: |
          case "${{ parameters.action }}" in
            "setup")
              echo "🚀 Setting up Kubernetes cluster..."
              
              # Fix repository issues
              sudo rm -f /etc/apt/sources.list.d/hashicorp.list
              sudo rm -f /etc/apt/sources.list.d/mikhailnov-ubuntu-pulseeffects-jammy.list
              sudo apt update 2>/dev/null || true
              
              # Install ansible
              sudo apt install -y ansible || {
                echo "Trying pip installation..."
                sudo apt install -y python3-pip
                pip3 install ansible
                export PATH="$HOME/.local/bin:$PATH"
              }
              
              ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
              ;;
            "reset")
              echo "🔄 Resetting Kubernetes cluster..."
              multipass exec k8s-master -- sudo bash -c "kubeadm reset -f && rm -rf /var/lib/etcd && rm -rf /etc/kubernetes/pki"
              multipass exec k8s-worker1 -- sudo kubeadm reset -f
              multipass exec k8s-worker2 -- sudo kubeadm reset -f
              echo "✅ Cluster reset complete"
              ;;
            "rejoin-workers")
              echo "🔗 Rejoining worker nodes..."
              # First ensure master is properly initialized
              MASTER_IP=$(multipass info k8s-master | grep IPv4 | awk '{print $2}')
              multipass exec k8s-master -- sudo bash -c "kubeadm reset -f && rm -rf /var/lib/etcd && rm -rf /etc/kubernetes/pki"
              multipass exec k8s-master -- sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=$MASTER_IP
              
              # Get new join command
              JOIN_CMD=$(multipass exec k8s-master -- sudo kubeadm token create --print-join-command)
              multipass exec k8s-worker1 -- sudo kubeadm reset -f
              multipass exec k8s-worker2 -- sudo kubeadm reset -f
              multipass exec k8s-worker1 -- sudo $JOIN_CMD
              multipass exec k8s-worker2 -- sudo $JOIN_CMD
              echo "✅ Workers rejoined"
              ;;
            "status")
              echo "📊 Kubernetes Cluster Status..."
              kubectl get nodes -o wide
              kubectl get pods --all-namespaces
              kubectl get svc --all-namespaces
              ;;
            "restart-services")
              echo "🔄 Restarting Kubernetes services..."
              multipass exec k8s-master -- sudo systemctl restart kubelet containerd
              multipass exec k8s-worker1 -- sudo systemctl restart kubelet containerd
              multipass exec k8s-worker2 -- sudo systemctl restart kubelet containerd
              echo "✅ Services restarted"
              ;;
          esac
    
    - task: Bash@3
      displayName: 'Setup kubectl and Verify (setup/rejoin only)'
      condition: and(succeeded(), in(variables['action'], 'setup', 'rejoin-workers'))
      inputs:
        targetType: 'inline'
        script: |
          # Setup kubectl
          multipass exec k8s-master -- sudo cat /etc/kubernetes/admin.conf > ~/.kube/config
          
          # Verify cluster
          echo "🔍 Cluster Status:"
          kubectl get nodes -o wide
          kubectl get pods --all-namespaces
          
          # Check if all nodes are ready
          NOT_READY=$(kubectl get nodes --no-headers | grep -v Ready | wc -l)
          if [ $NOT_READY -eq 0 ]; then
            echo "✅ All nodes are Ready!"
          else
            echo "⚠️ Some nodes are not Ready"
            kubectl get nodes
          fi